### ISSUE TITLE
LS1028ARDB: "tc filter add" commond doesn't working

### ISSUE THREAD

**Issue by LawKongYo** [nxp-real-time-edge-sw/real-time-edge-linux#1]
Hi
I want to run this kernel on LS1028ARDB, to use the TSN function of tc.
I have already turned on the configuration file with 'NET', 'NET_SCHED', 'NET_CLS_BASIC', 'NET_CLS_TCINDEX', 'NET_CLS_ROUTE4', 'NET_CLS_FW', 'NET_CLS_U32'. 'NET_CLS_RSVP', 'NET_CLS_RSVP6', 'NET_CLS_BPF'. 'NET_CLS_FLOWER', 'NET_EMATCH', 'NET_CLS_ACT', 'NET_CLS_FLOW'. 'NET_CLS_CGROUP'. 'NET_CLS_MATCHALL' to use the NET_CLS function.
With the kernel log. I can see the function tc_filter_init has been initialized during boot.

But when I use the following command line:
`tc qdisc add dev swp2 clsact`
`tc filter add dev swp2 ingress prio 1 u32 match ip src 192.168.0.5/24 action drop`
there is no ERROR condition, and this command doesn't work.
In function tc_setup_cb_add, judgement with 'tp->ops->hw_add' failed, and jump over.
Use following command line:
`tc filter show dev swp2 ingress`
print info:
_filter protocol all pref 1 u32 chain 0
_filter protocol all pref 1 u32 chain 0 fh 800: ht divisor 1_
_filter protocol all pref 1 u32 chain 0 fh 800::800 order 2048 key ht 800 bkt 0 terminal flowid ??? not_in_hw__
shows that the filter protocol doesn't set into the HW switch.

Is there any misconduct in my setup?
Looking forward to your reply.
Best wishes!

**Comment by vladimiroltean** [comment]
Hello,
The ocelot switch driver does not offload the u32 classifier, just flower.
Try:
```
tc filter add dev swp2 ingress protocol ip flower skip_sw src_ip 192.168.0.5 action drop
```

**Comment by LawKongYo** [comment]
> Hello, The ocelot switch driver does not offload the u32 classifier, just flower. Try:
> 
> ```
> tc filter add dev swp2 ingress protocol ip flower skip_sw src_ip 192.168.0.5 action drop
> ```

Thanks very much!
I used the config command in doc "REALTIMEEDGEUG_Rev2.1", with the fixed action chain, can successfully set the VCAP rules of action DROP.
`tc qdisc add dev swp2 clsact`
`tc filter add dev swp2 ingress chain 0 pref 49152 flower skip_sw action goto chain 21000`
`tc filter add dev swp2 ingress chain 21000  protocol ip flower skip_sw src_ip 192.168.3.15 action drop`

In the USER GUIDE 4.4.2 VCAP on LS1028A Felix switch, actions supported on LS1028A are: "**_trap, drop, police, vlan modify, vlan push(Egress)_**", but Table 62 Chain allocation, shows that I can set action "**_skbedit priority_**" with chain 10000.

**I want to make sure if it's possible to set the priority after TC filter?**

Looking forward to your reply.
Best wishes!

**Comment by vladimiroltean** [comment]
Yes, you can offload `skbedit priority` actions to either VCAP IS1 lookup 0, 1 or 2. You can see this selftest for an example:
https://github.com/torvalds/linux/blob/master/tools/testing/selftests/drivers/net/ocelot/tc_flower_chains.sh

**Comment by LawKongYo** [comment]
> Yes, you can offload `skbedit priority` actions to either VCAP IS1 lookup 0, 1 or 2. You can see this selftest for an example: https://github.com/torvalds/linux/blob/master/tools/testing/selftests/drivers/net/ocelot/tc_flower_chains.sh

Thanks very much!
What rules can be used to mark the DSCP value for the packet which is filtered in this real-time-edge-sw Kernel?

Looking forward to your reply.
Best wishes!
